version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "devRequirements.txt" }}
      - run:
          command: |
            virtualenv env
            source env/bin/activate
            pip install -r requirements.txt
            pip install -r devRequirements.txt
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "devRequirements.txt" }}
          paths:
            - "env"
      - run:
          command: |
            source env/bin/activate
            nosetests
